"""
Generate a grounded researcher profile from retrieved evidence.

This script has two modes:

1. Evidence-pack mode:
   Retrieves relevant chunks and writes them to JSON.

2. LLM profile mode:
   Sends the evidence pack to an OpenAI model and asks for a structured profile
   with citations and confidence notes.

The model is instructed to use only the supplied evidence. If evidence is weak
or missing, it should say so rather than inventing facts.
"""

import argparse
import json
import os
from pathlib import Path

from openai import OpenAI
from retrieve import retrieve


OUTPUT_DIR = Path("outputs")
DEFAULT_MODEL = "gpt-4.1-mini"


PROFILE_QUERIES = {
    "research_interests": (
        "research interests research areas expertise focuses on works on"
    ),
    "projects_and_grants": (
        "project grant funded funding award fellowship principal investigator "
        "PI co-investigator"
    ),
    "collaborators": (
        "collaborator collaboration co-author coauthored co-authored worked "
        "with team partner"
    ),
    "affiliations": (
        "affiliation affiliated institute centre center university department "
        "lab member fellow"
    ),
    "publications": (
        "publication paper article journal conference proceedings book chapter DOI"
    ),
}


SYSTEM_PROMPT = """
You are an academic intelligence analyst.

You build grounded researcher profiles from retrieved evidence.

Rules:
- Use only the supplied evidence pack.
- Do not invent projects, funders, collaborators, affiliations, or publications.
- If the evidence is unclear, say so in confidence_notes.
- Every substantive claim must cite one or more chunk_ids.
- Prefer concise, structured output over prose.
- Return valid JSON only.
"""


USER_PROMPT_TEMPLATE = """
Create a structured academic profile from this evidence pack.

Return JSON with this exact shape:

{
  "researcher_id": "...",
  "summary": "...",
  "research_interests": [
    {
      "claim": "...",
      "citations": ["chunk_id"],
      "confidence": 0.0
    }
  ],
  "projects_and_grants": [
    {
      "claim": "...",
      "citations": ["chunk_id"],
      "confidence": 0.0
    }
  ],
  "collaborators": [
    {
      "claim": "...",
      "citations": ["chunk_id"],
      "confidence": 0.0
    }
  ],
  "affiliations": [
    {
      "claim": "...",
      "citations": ["chunk_id"],
      "confidence": 0.0
    }
  ],
  "publications": [
    {
      "claim": "...",
      "citations": ["chunk_id"],
      "confidence": 0.0
    }
  ],
  "partnership_opportunities": [
    {
      "opportunity": "...",
      "rationale": "...",
      "supporting_citations": ["chunk_id"],
      "confidence": 0.0
    }
  ],
  "confidence_notes": [
    "..."
  ]
}

Evidence pack:
{evidence_pack_json}
"""


def build_evidence_pack(researcher_id, top_k):
    """
    Retrieve evidence chunks for each profile category.

    Parameters:
        researcher_id: Folder name under `data/processed`.
        top_k: Number of chunks to retrieve per category.

    Returns:
        Dictionary containing category-level retrieval results.
    """
    categories = {}

    for category, query in PROFILE_QUERIES.items():
        categories[category] = {
            "query": query,
            "evidence": retrieve(researcher_id, query, top_k=top_k),
        }

    return {
        "researcher_id": researcher_id,
        "categories": categories,
    }


def save_json(path, data):
    """
    Save a Python object as pretty JSON.
    """
    path.parent.mkdir(parents=True, exist_ok=True)

    with path.open("w", encoding="utf-8") as file:
        json.dump(data, file, indent=2, ensure_ascii=False)


def save_evidence_pack(researcher_id, evidence_pack):
    """
    Save the retrieved evidence pack as JSON.
    """
    output_path = OUTPUT_DIR / f"{researcher_id}_evidence_pack.json"
    save_json(output_path, evidence_pack)
    return output_path


def generate_profile_with_llm(evidence_pack, model):
    """
    Generate a structured profile using an OpenAI model.

    Parameters:
        evidence_pack: Retrieved evidence grouped by profile category.
        model: OpenAI model name.

    Returns:
        Parsed JSON profile generated by the model.
    """
    if not os.getenv("OPENAI_API_KEY"):
        raise RuntimeError(
            "OPENAI_API_KEY is not set. Export it before running LLM mode."
        )

    client = OpenAI()

    evidence_pack_json = json.dumps(evidence_pack, indent=2, ensure_ascii=False)
    user_prompt = USER_PROMPT_TEMPLATE.replace(
        "{evidence_pack_json}",
        evidence_pack_json
    )

    response = client.responses.create(
        model=model,
        input=[
            {
                "role": "system",
                "content": SYSTEM_PROMPT.strip(),
            },
            {
                "role": "user",
                "content": user_prompt,
            },
        ],
        text={
            "format": {
                "type": "json_object"
            }
        },
    )

    return json.loads(response.output_text)


def main():
    """
    Parse command-line arguments and generate a researcher evidence pack/profile.
    """
    parser = argparse.ArgumentParser(
        description="Generate a grounded academic researcher profile."
    )
    parser.add_argument(
        "researcher_id",
        help="Folder name under data/processed, e.g. natalia_efremova",
    )
    parser.add_argument(
        "--top-k",
        type=int,
        default=8,
        help="Number of evidence chunks per profile category.",
    )
    parser.add_argument(
        "--llm",
        action="store_true",
        help="Use an OpenAI model to generate the final structured profile.",
    )
    parser.add_argument(
        "--model",
        default=DEFAULT_MODEL,
        help=f"OpenAI model to use in LLM mode. Default: {DEFAULT_MODEL}",
    )

    args = parser.parse_args()

    evidence_pack = build_evidence_pack(args.researcher_id, args.top_k)
    evidence_path = save_evidence_pack(args.researcher_id, evidence_pack)

    print(f"Wrote evidence pack to {evidence_path}")

    if args.llm:
        profile = generate_profile_with_llm(evidence_pack, args.model)
        profile_path = OUTPUT_DIR / f"{args.researcher_id}_profile.json"
        save_json(profile_path, profile)

        print(f"Wrote generated profile to {profile_path}")


if __name__ == "__main__":
    main()